app = "sectors-guard"
primary_region = "sin"

# Using custom Dockerfile
[build]
  dockerfile = "Dockerfile.minimal"

[env]
PORT = "8080"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
size = "shared-cpu-1x"
memory = "1gb"

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "get"
    path = "/health"
    port = 8080
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false
    headers = {}